### ISSUE TITLE
21_DoSA-Open_Library source code missing from repository

### ISSUE THREAD

**Issue by geefer** [OpenActuator/DoSA-2D#1]
The code requires library code in directory 21_DoSA-Open_Library which is not in the repository.

Missing files are:

**21_DoSA-Open_Library\Notice.cs
21_DoSA-Open_Library\ManageFile.cs
21_DoSA-Open_Library\MessageListView.cs
21_DoSA-Open_Library\ReadWriteFile.cs**

**Comment by OpenActuator** [comment]
It is my mistake.
I upload that files.

Thank you.

**Comment by OpenActuator** [comment]
It was my mistake.
I upload that files.

Thank you.
