### ISSUE TITLE
Errors while trying to plot Current and Stroke results

### ISSUE THREAD

**Issue by geefer** [OpenActuator/DoSA-2D#2]
The plots from both the Stroke and Current experiments do not show up. The .csv files created during the experiment runs are correct but no plots are produced and errors are logged in the logfile as follows:

```
3/28/2020 1:32:23 PM, ReadWriteFile.cs, 731, readCSVRowData : Index was outside the bounds of the array.
3/28/2020 1:32:23 PM, FormMain.cs, 1762, plotStrokeResult : The number of rows in each column in the CSV file does not match.
3/28/2020 1:32:53 PM, ReadWriteFile.cs, 731, readCSVRowData : Index was outside the bounds of the array.
3/28/2020 1:32:53 PM, FormMain.cs, 1821, plotCurrentResult : The number of rows in each column in the CSV file does not match.
```

Without access to the source code for the library #1 I cannot debug this issue.

**Comment by OpenActuator** [comment]
I fixed that problem today.
It is so serious bug.

Thank you so much.
